Online doc
ZPI-2023-IST/Documentation pull request #7
Opened 2023-12-05 20:19 UTC by Kamil-Krawiec

2023-12-05 20:20 UTC, Kamil-Krawiec commented
API + online version of read the docs

2023-12-06 00:43 UTC, WiktorSa requested changes

2023-12-06 00:43 UTC, WiktorSa commented on source/api.rst
> +The `Runner` class initializes a FreeCell game and a corresponding translator. The `reset` method is used to reset the game.
"initializes a game" a nie "initializes a FreeCell game" gdyż opisujemy generalne działanie API bez podawania przykładu

2023-12-06 00:43 UTC, WiktorSa commented on source/api.rst
> +The **make_move** function, is an asynchronous event handler, it processes move requests from the RL via WebSocket.
To jest to make_move czy make_action? Bo nazwy funkcji są inne

2023-12-06 00:43 UTC, WiktorSa commented on source/index.rst
> +   api
Ja dałbym to api przed rl.

Czemu? Bo kolejność imo jest taka game -> translator -> api -> rl -> frontend -> visualization jak się pomyśli o działaniu systemu i jak już dałem uwagi to można to też zmienić po drodze

2023-12-06 00:45 UTC, WiktorSa commented
Dodatkowo jak dodajesz już te online_docs to imo należałoby dopisać jak je wygenerować/shostować dokumentację online. Brakuje mi takiego dopisku w README

2023-12-07 14:33 UTC, merged